server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
zuul:
  routes:
    api-index:
      path: /index/api/**
      serviceId: index
    api-comment:
      path: /comment/api/**
      serviceId: comment
    api-user:
      path: /user/api/**
      serviceId: user
    api-article:
      path: /article/api/**
      serviceId: article
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000